# Site settings
title: "Mathematical Foundations of Machine Learning - Part 2"
description: "UM6P - 2025-2026"
url: "https://hm-ai.github.io"
baseurl: "/UM6P"

# Theme
remote_theme: clayh53/tufte-jekyll

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Site info
author:
  name: "Hachem Madmoun"
  email: "h.madmoun@ic.ac.uk"

# Navigation (used by custom header)
navigation:
  - title: Home
    url: /
  - title: Syllabus
    url: /syllabus/
  - title: Feedback Track
    url: /progress/

# Tufte settings
tufte_features:
  sidenotes: true
  marginnotes: true

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - .idea
  - "*.csv"
  - "*.ipynb"
